//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.KYCONGCHITIET = new HashSet<KYCONGCHITIET>();
            this.tb_BaoHiem = new HashSet<tb_BaoHiem>();
            this.tb_HopDong = new HashSet<tb_HopDong>();
            this.tb_KhenThuong_KyLuat = new HashSet<tb_KhenThuong_KyLuat>();
            this.tb_Luong_NV = new HashSet<tb_Luong_NV>();
            this.tb_PhanCong = new HashSet<tb_PhanCong>();
            this.tb_PhuCap_NhanVien = new HashSet<tb_PhuCap_NhanVien>();
            this.tb_TaiKhoan = new HashSet<tb_TaiKhoan>();
            this.tb_TangCa = new HashSet<tb_TangCa>();
            this.tb_TinhTrangNV = new HashSet<tb_TinhTrangNV>();
            this.tb_UngLuong = new HashSet<tb_UngLuong>();
        }
    
        public string MaNV { get; set; }
        public string TenNV { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string SDT { get; set; }
        public string DiaChi { get; set; }
        public string CCCD { get; set; }
        public byte[] HinhAnh { get; set; }
        public Nullable<int> MaTD { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
        public string NoiCap { get; set; }
        public string TonGiao { get; set; }
        public string DanToc { get; set; }
        public Nullable<int> DangLamViec { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KYCONGCHITIET> KYCONGCHITIET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_BaoHiem> tb_BaoHiem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_HopDong> tb_HopDong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_KhenThuong_KyLuat> tb_KhenThuong_KyLuat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Luong_NV> tb_Luong_NV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_PhanCong> tb_PhanCong { get; set; }
        public virtual tb_TrinhDo tb_TrinhDo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_PhuCap_NhanVien> tb_PhuCap_NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_TaiKhoan> tb_TaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_TangCa> tb_TangCa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_TinhTrangNV> tb_TinhTrangNV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_UngLuong> tb_UngLuong { get; set; }
    }
}
