//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_BangLuong
    {
        public int ID { get; set; }
        public Nullable<int> MAKYCONG { get; set; }
        public string MaNV { get; set; }
        public string TenNV { get; set; }
        public Nullable<double> NgayCongTrongThang { get; set; }
        public Nullable<double> NgayPhep { get; set; }
        public Nullable<double> KhongPhep { get; set; }
        public Nullable<double> NgayLe { get; set; }
        public Nullable<double> NgayChuNhat { get; set; }
        public Nullable<double> NgayThuong { get; set; }
        public Nullable<double> TangCa { get; set; }
        public Nullable<double> PhuCap { get; set; }
        public Nullable<double> UngLuong { get; set; }
        public Nullable<double> BHYT { get; set; }
        public Nullable<double> BHTN { get; set; }
        public Nullable<double> BHXH { get; set; }
        public Nullable<double> ThucLanh { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    }
}
