//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PhuCap_NhanVien
    {
        public int ID { get; set; }
        public int MaPCap { get; set; }
        public string MaNV { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string NoiDung { get; set; }
        public Nullable<double> SoTien { get; set; }
        public Nullable<int> Delete_by { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual tb_PhuCap tb_PhuCap { get; set; }
    }
}
