//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_TangCa
    {
        public int ID { get; set; }
        public string MaNV { get; set; }
        public Nullable<int> nam { get; set; }
        public Nullable<int> thang { get; set; }
        public Nullable<double> SoGio { get; set; }
        public Nullable<int> IDLoaiCa { get; set; }
        public Nullable<double> SoTien { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual tb_LoaiCa tb_LoaiCa { get; set; }
    }
}
